apiVersion: v1
kind: Namespace
metadata:
  name: netmon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netmon
  namespace: netmon
  labels:
    app: netmon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netmon
  template:
    metadata:
      labels:
        app: netmon
    spec:
      containers:
      - name: netmon
        image: forana/netmon:latest
        env:
        - name: DATABASE_FILE
          value: /data/netmon.sqlite
        - name: CHECK_VARIANCE
          value: "5"
        resources:
          requests:
            memory: "20Mi"
            cpu: "10m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        hostPath: 
          path: /data/netmon
          type: Directory
